# Generated by Django 3.0.3 on 2020-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=30)),
                ('busNumber', models.IntegerField()),
                ('govNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
