# Generated by Django 3.0.3 on 2020-03-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='StopName',
            new_name='Stops',
        ),
    ]
