# Generated by Django 3.0.3 on 2020-03-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20200320_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='Stops',
        ),
    ]
