# Generated by Django 3.0.3 on 2020-03-25 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_remove_route_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='routeStop',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
        ),
    ]
