# Generated by Django 3.0.3 on 2020-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_route_routestop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='routeName',
            field=models.CharField(max_length=101),
        ),
    ]
