# Generated by Django 3.0.3 on 2020-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20200325_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='routeStop',
        ),
        migrations.AddField(
            model_name='route',
            name='idStop',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='route',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='route',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='route',
            name='stopName',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
