# Generated by Django 3.0.3 on 2020-03-26 17:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20200325_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stopName',
        ),
        migrations.AddField(
            model_name='route',
            name='Stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=None, size=None),
        ),
    ]
