# Generated by Django 3.0.3 on 2020-03-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20200326_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='idStop',
        ),
    ]
